# Generated by Django 4.1.2 on 2022-10-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Fashion', 'Fashion'), ('Toys', 'Toys')], default=('Other', 'Other'), max_length=150),
        ),
        migrations.AddField(
            model_name='products',
            name='last_offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.TextField(),
        ),
    ]
